version: '3.3'
services:
  zammad-postgresql:
    image: postgres:15.4
    container_name: zammad-postgresql
    environment:
      - POSTGRES_USER=zammad
      - POSTGRES_PASSWORD=zammad
      - POSTGRES_DB=zammad
      - POSTGRES_MAX_CONNECTIONS=100
      - POSTGRES_SHARED_BUFFERS=256MB
    command: 
      - "postgres"
      - "-c"
      - "max_connections=100"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - zabbix-net

  zammad-elasticsearch:
    image: elasticsearch:7.17.9
    container_name: zammad-elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - zabbix-net

  zammad-redis:
    image: redis:7.0
    container_name: zammad-redis
    command: redis-server --save "" --appendonly no
    networks:
      - zabbix-net

  zammad-init:
    image: zammad/zammad-docker-compose:latest
    container_name: zammad-init
    command: ["zammad-init"]
    depends_on:
      - zammad-postgresql
      - zammad-elasticsearch
      - zammad-redis
    environment:
      - POSTGRESQL_HOST=zammad-postgresql
      - POSTGRESQL_USER=zammad
      - POSTGRESQL_PASS=zammad
      - ELASTICSEARCH_HOST=zammad-elasticsearch
      - ELASTICSEARCH_PORT=9200
      - REDIS_URL=redis://zammad-redis:6379
      - ZAMMAD_RAILSSERVER_HOST=zammad-railsserver
    networks:
      - zabbix-net

  zammad-railsserver:
    image: zammad/zammad-docker-compose:latest
    container_name: zammad-railsserver
    command: ["zammad-railsserver"]
    depends_on:
      - zammad-postgresql
      - zammad-elasticsearch
      - zammad-redis
    environment:
      - POSTGRESQL_HOST=zammad-postgresql
      - POSTGRESQL_USER=zammad
      - POSTGRESQL_PASS=zammad
      - ELASTICSEARCH_HOST=zammad-elasticsearch
      - ELASTICSEARCH_PORT=9200
      - REDIS_URL=redis://zammad-redis:6379
    networks:
      - zabbix-net

  zammad-scheduler:
    image: zammad/zammad-docker-compose:latest
    container_name: zammad-scheduler
    command: ["zammad-scheduler"]
    depends_on:
      - zammad-railsserver
    environment:
      - POSTGRESQL_HOST=zammad-postgresql
      - POSTGRESQL_USER=zammad
      - POSTGRESQL_PASS=zammad
      - POSTGRESQL_OPTIONS=?pool=50
      - ELASTICSEARCH_HOST=zammad-elasticsearch
      - ELASTICSEARCH_PORT=9200
      - REDIS_URL=redis://zammad-redis:6379
    networks:
      - zabbix-net

  zammad-websocket:
    image: zammad/zammad-docker-compose:latest
    container_name: zammad-websocket
    command: ["zammad-websocket"]
    depends_on:
      - zammad-railsserver
    environment:
      - POSTGRESQL_HOST=zammad-postgresql
      - POSTGRESQL_USER=zammad
      - POSTGRESQL_PASS=zammad
      - ELASTICSEARCH_HOST=zammad-elasticsearch
      - ELASTICSEARCH_PORT=9200
      - REDIS_URL=redis://zammad-redis:6379
    networks:
      - zabbix-net

  zammad-nginx:
    image: zammad/zammad-docker-compose:latest
    container_name: zammad-nginx
    command: ["zammad-nginx"]
    depends_on:
      - zammad-railsserver
    ports:
      - "8083:8080"
    environment:
      - NGINX_SERVER_SCHEME=http
      - NGINX_SERVER_NAME=localhost
      - REDIS_URL=redis://zammad-redis:6379
    networks:
      - zabbix-net

networks:
  zabbix-net:
    external: true
    name: zabbix_server_70_zabbix-net

volumes:
  postgres-data:
  elasticsearch-data: